#! /bin/bash
cd ~/Documents/Thesis/dpdk-18.11.2/dpdk-stable-18.11.2/usertools
./dpdk-devbind.py -u 0000:03:00.0
cd ~/Documents/Thesis/ntop/PF_RING/kernel
insmod pf_ring.ko enable_tx_capture=0
cd ../drivers/intel/ixgbe/ixgbe-5.5.3-zc/src
./load_driver.sh
